coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%
  ignore:
     - "tests/.*"
     - "examples/.*"
     - "src/metatensor/models/experimental/.*"

comment: false
