coverage:
  status:
    project:
      default:
        target: 80%
    patch: off
  ignore:
    - "tests/.*"
    - "examples/.*"
    # architectures are not part of the coverage
    - "src/metatensor/models/experimental/.*"

comment: false
