# default hyperparameters for the SOAP-BPNN model
model:
  soap:
    cutoff: 5.0  # radial cutoff (Å)
    max_radial: 8  # number of radial basis functions
    max_angular: 6  # maximum degree of spherical harmonics
    atomic_gaussian_width: 0.3  # width of atomic Gaussian (Å)
    radial_basis:
      Gto: {}
    center_atom_weight: 1.0  # weight of center atom in SOAP
    cutoff_function:
      ShiftedCosine:
        width: 1.0  # width of shifted cosine cutoff function (Å)
    radial_scaling:
      Willatt2018:
        rate: 1.0
        scale: 2.0
        exponent: 7.0

  bpnn:
    layernorm: true  # whether to use layer normalization
    num_hidden_layers: 2  # number of hidden layers
    num_neurons_per_layer: 32  # number of neurons per hidden layer

training:
  batch_size: 8  # batch size
  num_epochs: 100  # number of training epochs
  learning_rate: 0.001  # learning rate
  log_interval: 10  # write a line to the log every 10 epochs
  checkpoint_interval: 25  # save a checkpoint every 25 epochs
