model:
  soap:
    num_pseudo_species: 4
    cutoff_radius: 5.0
    basis_cutoff: 400
    radial_basis_type: 'physical'
    basis_scale: 3.0
    trainable_basis: true

  bpnn:
    num_hidden_layers: 2
    num_neurons_per_layer: 32
    activation_function: SiLU  # only SiLU is supported for the moment

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  patience: 50
  scheduler_patience: 10
  scheduler_factor: 0.8  
  log_interval: 10
  checkpoint_interval: 25
  per_atom_targets: []
