architecture:
  name: experimental.soap_bpnn
  training:
    batch_size: 16
    num_epochs: 100
    learning_rate: 0.01

# Section defining the parameters for system and target data
training_set:
  systems: "ethanol_reduced_100.xyz"
  targets:
    energy:
      key: "energy"
      unit: "kcal/mol"  # very important to run simulations

validation_set: 0.1
test_set: 0.0
